# Basic Information
title: Anqi Hu
position: Postdoctoral Fellow
affiliation: Department of Psychology, Western University
affiliation_link: https://www.uwo.ca/psychology/
email: ahu233 (at) uwo.ca

# Search Engine Optimization (SEO)
keywords: Anqi Hu, language development, autism, statistical learning, multisensory learning, developmental cognitive neuroscience
description: Personal academic website of Anqi Hu, a postdoctoral fellow studying language development, social communication, and multisensory learning in children.
canonical: https://anqihu2.github.io/

# Links
cv_link: ./assets/files/CV_AnqiHu_academic.pdf

github_link: https://github.com/anqihu2/
linkedin: https://www.linkedin.com/in/anqi-hu-7b797a280/

# Images
avatar: ./assets/img/prof_pic.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: true

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
